baseURL = "https://www.tetizeraz.online/"
languageCode = "pt-br"
title = "Tet's Blog"
themesDir = "themes"
theme = "hyde"
author = "Tet"
sectionPagesMenu = "main"

[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts/"
weight     = 10

[[menu.main]]
identifier = "bipolar"
name       = "Bipolaridade"
url        = "/bipolar/"
weight     = 20

[[menu.main]]
identifier = "computer witch"
name       = "Computer OS witch"
url        = "/computer-witch/"
weight     = 20

[[menu.main]]
identifier = "Licença/License"
name       = "Licença/License"
url        = "/licença/"
weight     = 30

[params]
    themeColor = "theme-base-08"
    description = "Jovem de 24 anos tentando ser jornalista."